### ISSUE TITLE
Installation error in "laravel/framework": "^7.24",

### ISSUE THREAD

**Issue by ghost** [jhoff/blade-vue-directive#7]
Problem 1
    - Installation request for jhoff/blade-vue-directive ^2.1 -> satisfiable by jhoff/blade-vue-directive[2.1.0].
    - Conclusion: remove laravel/framework v7.27.0
    - Conclusion: don't install laravel/framework v7.27.0
    - jhoff/blade-vue-directive 2.1.0 requires laravel/framework ^5.4|6.* -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v7.27.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v7.27.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.27.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.27.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.27.0].
    - Can only install one of: laravel/framework[5.4.x-dev, v7.27.0].
    - Installation request for laravel/framework (locked at v7.27.0, required as ^7.24) -> satisfiable by laravel/framework[v7.27.0].

Please give a solution

**Comment by jhoff** [comment]
Please try again as support for Laravel 7/8 has been added.
